version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  reviewers:
  - HunterAP23
  assignees:
  - HunterAP23
  allow:
  - dependency-type: direct
  - dependency-type: indirect
